version: '3.1'

services:
  db:
    image: postgres:13
    container_name: db
    restart: always
    environment:
      # postgresql://postgres:example@localhost/db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: db
    ports:
      - "5432:5432"

#  pgadmin:
#    image: dpage/pgadmin4:4.8
#    container_name: db_pgadmin_go
#    restart: always
#    ports:
#      - 8080:80
#    links:
#      - db
#    environment:
#      PGADMIN_DEFAULT_EMAIL: user@domain.com
#      PGADMIN_DEFAULT_PASSWORD: SuperSecret
